# format = """
# [ã‚·ãƒ³ã‚¸ãã‚“](bold green)[@](bold red)[åˆå·æ©Ÿ](bold blue)[ğŸ™†](blue)
# [â”‚](bold green)$directory$package
# [â””â”€>](bold green) """

format = """
[åˆå·æ©Ÿ](bold blue)[ @ ](blue)$all
[ â”‚](green)
[ â””â”€>](green) $character
"""

add_newline = true

[line_break]
disabled = true

[character]
# disabled = true
error_symbol = "[ğŸ™… ](bold red)"
success_symbol = "[ğŸ™† ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# [status]
# disabled = false
# symbol = "[ğŸ™…](bold red)"
# success_symbol = "[ğŸ™†](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# sigint_symbol = "ğŸ‘"
# not_found_symbol = "ğŸ™…"
# format = "[$symbol]($style) "
# map_symbol = true
# pipestatus = true
# style = "bold red"

# [time]
# disabled = false

[cmd_duration]
format = "[âŒ› $duration]($style) "
style = "bold yellow"

[directory]
truncation_length = 3
truncation_symbol = "" #"â€¦ "
format = "[$path]($style)[ $read_only]($read_only_style)"
style = "bold cyan"
read_only = "ğŸ”’"
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) " 
repo_root_style = "bold green"
home_symbol = "ğŸ "
